url: http://doublehappy.media
baseurl: ""

# Site settings
title: DOUBLE HAPPY MEDIA
email: your-email@domain.com
description: "DOUBLE HAPPY MEDIA specialize in producing New Zealand Documentaries that focus on people and culture."


# Team names, titles and social links
people:
- name: Michael Lamb
  pic: 1
  position: Writer/Producer
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Richard Riddiford
  pic: 2
  position: Director/Producer
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

- name: Athena Rhodes
  pic: 3
  position: Forever Intern
  social:
#    - title: twitter
#      url: rhodesathena

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty